export default () => [
  <link
    rel='apple-touch-icon'
    sizes='180x180'
    href='/static/icons/apple-touch-icon.png?v=2'
  />,
  <link
    rel='icon'
    type='image/png'
    sizes='32x32'
    href='/static/icons/favicon-32x32.png?v=2'
  />,
  <link
    rel='icon'
    type='image/png'
    sizes='16x16'
    href='/static/icons/favicon-16x16.png?v=2'
  />,
  <link
    rel='manifest'
    href='/static/icons/site.webmanifest?v=2'
  />,
  <link
    rel='mask-icon'
    href='/static/icons/safari-pinned-tab.svg?v=2'
    color='#5bbad5'
  />,
  <meta
    name='msapplication-TileColor'
    content='#da532c'
  />,
  <meta
    name='theme-color'
    content='#323945'
  />
]
