query meLogin{
  me {
    firstName
	  id
    teams {
      edges {
        node {
          id
          name
          socialProfiles{
            edges{
              node{
                id
                name
                socialNetwork
                profilePicture
                facebookPageName
              }
            }
          }
        }
      }
    }
  }
}
