query fetchTeamRoles($id: ID!) {
  team(id: $id) {
    id
    name
    teamRoles {
      edges {
        node {
          id
          role
          user {
            id
            email
            firstName
            lastName
          }
        }
      }
    }
  }
}